// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgI6xRItLG6rtj7td5DXoPL-XxNmApqi4',
    appId: '1:462766812324:web:546c8ae2b667fd4d160a31',
    messagingSenderId: '462766812324',
    projectId: 'exmoor-underwear',
    authDomain: 'exmoor-underwear.firebaseapp.com',
    storageBucket: 'exmoor-underwear.appspot.com',
    measurementId: 'G-KW3L14ZCR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5kvPnPVMzlsQTXX7X1Ykv2LHCokzDzd4',
    appId: '1:462766812324:android:d4f0aff8682d152c160a31',
    messagingSenderId: '462766812324',
    projectId: 'exmoor-underwear',
    storageBucket: 'exmoor-underwear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDelWkd3lebcjo8pEuwb-OkQW7aojkAMFA',
    appId: '1:462766812324:ios:0e3f08d68e767dd8160a31',
    messagingSenderId: '462766812324',
    projectId: 'exmoor-underwear',
    storageBucket: 'exmoor-underwear.appspot.com',
    iosBundleId: 'com.example.exmoorUnderwear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDelWkd3lebcjo8pEuwb-OkQW7aojkAMFA',
    appId: '1:462766812324:ios:f94ce8c2b04c432e160a31',
    messagingSenderId: '462766812324',
    projectId: 'exmoor-underwear',
    storageBucket: 'exmoor-underwear.appspot.com',
    iosBundleId: 'com.example.exmoorUnderwear.RunnerTests',
  );
}
